### ISSUE TITLE
Handling of BCE dates

### ISSUE THREAD

**Issue by gregallensworth** [OpenHistoricalMap/decimaldate-javascript#3]
It came to our attention a few days ago that the handling for BCE dates is not correct. 0000 is accepted, and refers to 1 BCE.

@1ec5 provided some reference dates inRefer to https://github.com/OpenHistoricalMap/leaflet-ohm-timeslider-v2/pull/10#discussion_r1376786108 but I believe them to be incorrect, and my math keeps giving reliable answers that are not the same as what was listed there. Could we please take a moment for some fact checking, so I can get the math right in both directions?

**Comment by gregallensworth** [comment]
**A number line**

Decimal date 0 would be the precise boundary between 1 BCE and 1 CE, also known as 0000-12-31 and 0001-01-01

On a number line, the absolute value (magnitude) increases as we go further from 0. Thus for BCE dates January is further from 0. For example:
- CE years, positive numbers, decimal portion increases toward December
  - January 1 of 1 CE would be `+1/365` = 0.001370
  - December 31 of 1 CE would be `+364/365` = 0.998630
- BCE years, negative numbers, decimal portion increases toward January
  - December 31 of 1 BCE would be `-1/366` = -0.001366
  - January 1 of 1 BCE would be `-365/366` = -0.998633
- the 0 origin is the cusp between 0000-12-31 and 0001-01-01
  - The value -0.5 would be 6 months before the 0 origin, closer to July 1 of 1 BCE (0000-07-01).
  - The value +0.5 would be 6 months after the 0 origin, closer to July 1 of 1 CE (0001-07-01).

(the exact numbers are off by `0.5/365` or `0.5/366` since decimaldate uses noon of the target day; stick to the larger point here)

**Prior reference points**

As such, some prior points provided as reference, I think are not accurate:

- "−1.0 is -0001-01-01, 1/1/2 BCE is Beginning of the year 2 BCE"
  - January 1 of 2 BCE would be almost two years before the 0 origin, more like -1.998
  - One year before the cusp between 1 BCE and 1 CE, would be -1.0 or 0000-01-01 That would be January of 1 BCE, not of 2 BCE.

- "−0.5 is -0001-07-01 is 7/1/2 BCE is Middle of the year 2 BCE"
  - -0.5 would be six months before the 0 origin, so the middle of 1 BCE, 0000-07-01
  - -0001-07-01 would indeed be the middle of 2 BCE, but that's 18 months before the 0 origin, so more like -1.5.

- "0.5 is 0000-07-01 is 7/1/1 BCE is Middle of the year 1 BCE"
  - +0.5 would be six months after the 0 origin, so July 1 1 CE
  - 0000-07-01 is the middle of 1 BCE, so 6 months before the 0 origin, so more like -0.5

**Mathematical reference points**

I think that a correct table of reference dates would be as follows:

true decimal | decimal + 1 | iso | comment
--- | --- | --- | ---
-1.998633 | -0.998633 | -0001-01-01 | first day of 2 CE, most negative (highest decimal portion) day of the year
-1.001366 | -0.001366 | -0001-12-31 | the last day of 2 BCE, least negative (lowest decimal portion) day of the year
-0.998633 | 0.001367 | 0000-01-01 | first day of 1 BCE, most negative (highest decimal portion) day of the year
-0.5 | 0.5 | 0000-07-02 | middle of 1 BCE, 6 months before the 0 origin of Jan 1 1 CE
-0.001366 | 0.998634 | 0000-12-31 | the last day of 1 BCE, least negative (lowest decimal portion) day of the year
0 | 1 | cusp | the cusp between Dec 31 1 BCE (0000-12-31) and Jan 1 1 CE (0001-01-01)
+0.001369 | +1.001369 | 0001-01-01 | the first day of 1 CE, least positive day of the year
+0.5 | +1.5 | 0001-07-01 | middle of 1 CE, 6 months after the 0 origin of Jan 1 1 CE
+0.998631 | +1.998631 | 0001-12-31 | last day of 1 CE, most positive day of the year
+1.001369 | +2.001369 | 0002-01-01 | the first day of 2 CE, least positive day of the year
+1.998631 | +2.998631 | 0002-12-31 | last day of 2 CE, most positive day of the year

**Comment by 1ec5** [comment]
Unfortunately, I think this table reflects one of the many intermediate stages of the table in https://github.com/OpenHistoricalMap/leaflet-ohm-timeslider-v2/pull/10#discussion_r1376786108 where I had so thoroughly confused myself. If we extend your table out to the present, then it is currently the year 2023, represented in ISO 8601 as 2023 but in decimal years as 2022. This doesn’t seem to be correct. The table would be correct if you increase each cell in the “decimal” column by one. That is, the “cusp” is actually the cusp of 1 in all three representations, because there’s no year 0 in the formatted representation.

**Comment by gregallensworth** [comment]
> If we extend your table out to the present, then it is currently the year 2023, 
> represented in ISO 8601 as 2023 but in decimal years as 2022. This doesn’t seem to be correct.

Mathematically it is correct: here in November 2023 we are 2022.9 years away from the 0 origin (which was called 0001-01-01). Similarly, on January 1 of 2 CE 0002-01-01 it was 1 year after the 0001-01-01 origin. They started counting at 1 so the time distances are off by 1.

But per our chat, I will artificially add 1 to all of the dates so the 0 mark is the cusp of 1 BCE and 2 BCE instead of true 0, so that positive/CE years look prettier.

**Comment by gregallensworth** [comment]
New code has been merged, using the math above.

- full rewrite and cleanup
- better docs and more tests
- includes the +1 offset as requested
